version: '3.4'

services:
  asoc:
    image: asoc
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  asoc-front:
    image: asoc-front
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - 80:80
  asoc-pgsql:
    image: asoc-pgsql
    environment:
      POSTGRES_DB: "asocdb"
      POSTGRES_USER: "asocuser"
      POSTGRES_PASSWORD: "asocpass"
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - "5432:5432"